backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}          
          - {label: Logo, name: image, widget: image}
          - {label: Banner Image, name: bannerimage, widget: image}
          - {label: About Us, name: aboutus, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Heading, name: heading, widget: string},{label: Text Content, name: textcontent, widget: text},{label: Image, name: image, widget: image}]}
          - {label: Our Services, name: ourservice, widget: object, fields: [{label: Service Title, name: servicetitle, widget: string, required: false}, {label: Services List, name:  servicelist, widget: list, fields: [{label: Heding, name: heading, widget: string, required: false}, {label: Description, name: description, widget: text, required: false},{label: Image, name: image, widget: image, required: false}]}]}         
          - {label: Our Portfolio, name: portfolio, widget: object, fields: [{label: Portfolio Title, name: portfoliotitle, widget: string , required: false}, {label: Portfolio List, name: portfoliolist, widget: list, fields: [{label: Portfolio Image, name: portfolioimage, widget: image, required: false}, {label: Portfolio Heading, name: portfolioheading, widget: string, required: false}, {label: Description, name: description, widget: text, required: false}, {label: URL, name: url, widget: string, required: false}]}] }
          - {label: Our Approach, name: ourapproach, widget: object, fields: [{label: Our Approach Title, name: ourapproachtitle, widget: string, required: false},{label: Our approach List, name: ourapproachlist, widget: list, fields: [{label: Icon image, name: iconimage, widget: image, required: false},{label: Heading, name: heading, widget: string, required: false},{label: Description, name: description, widget: text, required: false}]}]}
          - {label: Our Team, name: ourteam, widget: object, fields: [{label: Our Team Title, name: ourteamtitle, widget: string, required: false},{label: Team List, name: teamlist, widget: list, fields: [{label: Name, name: name, widget: string, required: false},{label: Designation, name: designation, widget: string, required: false},{label: Linkedin Profile Link, name: linkedinprofilelink, widget: string, required: false}, {label: Image, name: image, widget: image, required: false}]}]}
          - {label: Contact Us, name: contactus, widget: object, fields: [{label: Contact Us Title, name: contactustitle, widget: string, required: false}, {label: Heading, name: heading, widget: string, required: false},{label: Company Id, name: companyid, widget: string, required: false},{label: Company Address, name: companyaddress, widget: text, required: false},{label: Company Logo, name: companylogo, widget: image, required: false}]}
          - {label: Footer, name: footer, required: false,  widget: object, fields: [{label: Copy Right, name: copyright, widget: string, required: false},{label: Connect With Social Media, name: socialmedialist, required: false, widget: list, fields: [{label: Social Media Name, name: socialmedianame, widget: string, required: false},{label: Social Media Icon image, name: socialmediaiconimage, widget: image, required: false},{label: Media Link, name: medialink, widget: text, required: false}]}]}